[buildPlans.IoseptaMono]
family = "Iosepta Mono"
spacing = "normal"
serifs = "sans"
noCvSs = true  # disables cv##/ss## features for decreased file size
exportGlyphNames = false  # set to true if Kitty ligature support is needed

  [buildPlans.IoseptaMono.namingOverride]
  version = "1.1.0"
  description = "Custom Iosevka font build, largely based off Input Mono."
  urlVendor = "https://github.com/roccojiang/iosepta-mono"
  urlDesigner = "https://typeof.net/Iosevka/"

  # Override xHeight to be slightly taller than the default 520
  [buildPlans.IoseptaMono.metricOverride]
  xHeight = 540

  # Build only the following weights
  [buildPlans.IoseptaMono.weights]
  Medium = "default.Medium"
  SemiBold = "default.SemiBold"
  Bold = "default.Bold"

    # Override "regular" weight to be slightly bolder than the default 400
    [buildPlans.IoseptaMono.weights.Regular]
    shape = 420
    menu = 400
    css = 400

  # Build only the "normal" width variant (omit "expanded")
  [buildPlans.IoseptaMono.widths]
  Normal = "default.Normal"

  # Omit the "oblique" slope variant
  [buildPlans.IoseptaMono.slopes]
  Upright = "default.Upright"
  Italic = "default.Italic"

  [buildPlans.IoseptaMono.variants]
  inherits = "ss18"  # Input Mono style

  [buildPlans.IoseptaMono.variants.design]
  one = "no-base"
  three = "flat-top-serifless"
  four = "semi-open-serifless"
  five = "upright-arched-serifless"
  six = "straight-bar"
  seven = "bend-serifless-crossbar"
  nine = "straight-bar"
  zero = "dotted"

  f = "serifless"
  g = "double-storey-open"
  l = "serifed-semi-tailed"

  lower-alpha = "crossing"
  lower-gamma = "casual"
  lower-lambda = "straight-turn"
  lower-tau = "semi-tailed"
  lower-upsilon = "casual-serifless"

  asterisk = "penta-low"
  underscore = "high"
  paren = "large-contour"
  brace = "curly-flat-boundary"
  number-sign = "upright"
  percent = "rings-segmented-slash"
  bar = "force-upright"
  lig-ltgteq = "slanted"

  [buildPlans.IoseptaMono.ligations]
  inherits = "default-calt"
  enables = [
    "counter-arrow-l", "counter-arrow-r",  # >>=, etc.
	  "brack-bar",  # [| |]
	  "logic",  # /\ and \/
  ]
  disables = [
	  "llggeq",  # allows <<= and >>= to use their "counter-arrow-" forms
  ]


# Normal spacing, without ligatures
[buildPlans.IoseptaMonoNoLig]
family = "Iosepta Mono NoLig"
spacing = "normal"
serifs = "sans"
noCvSs = true
noLigation = true
exportGlyphNames = false

weights.inherits  = "buildPlans.IoseptaMono"
widths.inherits   = "buildPlans.IoseptaMono"
slopes.inherits   = "buildPlans.IoseptaMono"
variants.inherits = "buildPlans.IoseptaMono"

  [buildPlans.IoseptaMonoNoLig.namingOverride]
  version = "1.1.0"
  description = "Custom Iosevka font build, largely based off Input Mono."
  urlVendor = "https://github.com/roccojiang/iosepta-mono"
  urlDesigner = "https://typeof.net/Iosevka/"

  # Same xHeight as above
  [buildPlans.IoseptaMonoNoLig.metricOverride]
  xHeight = 540


# Terminal spacing, with ligatures
[buildPlans.IoseptaMonoTerm]
family = "Iosepta Mono Term"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

weights.inherits  = "buildPlans.IoseptaMono"
widths.inherits   = "buildPlans.IoseptaMono"
slopes.inherits   = "buildPlans.IoseptaMono"
variants.inherits = "buildPlans.IoseptaMono"

  [buildPlans.IoseptaMonoTerm.namingOverride]
  version = "1.1.0"
  description = "Custom Iosevka font build, largely based off Input Mono."
  urlVendor = "https://github.com/roccojiang/iosepta-mono"
  urlDesigner = "https://typeof.net/Iosevka/"

  # Same xHeight as above
  [buildPlans.IoseptaMonoTerm.metricOverride]
  xHeight = 540

  # Same ligations as above
  [buildPlans.IoseptaMonoTerm.ligations]
  inherits = "default-calt"
  enables = [
    "counter-arrow-l", "counter-arrow-r",  # >>=, etc.
	  "brack-bar",  # [| |]
	  "logic",  # /\ and \/
  ]
  disables = [
	  "llggeq",  # allows <<= and >>= to use their "counter-arrow-" forms
  ]


[collectPlans.IoseptaMono]
from = [
  "IoseptaMono",
  "IoseptaMonoNoLig",
  "IoseptaMonoTerm"
]
